"""empty message

Revision ID: bd755ee46993
Revises: f6ce85342558
Create Date: 2018-03-09 23:50:34.652886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd755ee46993'
down_revision = 'f6ce85342558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logs_dt'), 'logs', ['dt'], unique=False)
    op.create_index(op.f('ix_people_id'), 'people', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_id'), table_name='people')
    op.drop_index(op.f('ix_logs_dt'), table_name='logs')
    # ### end Alembic commands ###
